### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by danishravian** [litchfield/django-fastsitemaps#6]
Hello,

I am new to django and python. So, please tell me how can I install it.

Thanks

**Comment by anderspetersson** [comment]
Welcome to Python and Django!

Looks lite this package dsnt exist on PYPI (that should be fixed) so you'l need to install from github.

Hopefully you have pip installed, then just run 
```
pip install -e git://github.com/litchfield/django-fastsitemaps.git#egg=django-fastsitemaps
```

if pip isnt installed, upgrade to the latest Python version (currently 2.7.9 or 3.4.2).

@litchfield you should do a release on PYPI.

**Comment by anderspetersson** [comment]
Also, before this issue is closed, Installation should be documented.

**Comment by danishravian** [comment]
Thanks Anderson,

I am using windows machine and this command does not work on windows. 
It says: cannot find command git. 

Also I think egg thing also does not work on windows. I was trying to install django-static-sitemaps and it was giving me egg_info error: https://github.com/xaralis/django-static-sitemaps/issues/30

So, please tell me any easy method for windows.

Thanks :)

**Comment by anderspetersson** [comment]
@danishravian You need to install git. I have not used Windows in a decade, but I've heard the best way to install git on windows is to install github's client. https://windows.github.com/

**Comment by danishravian** [comment]
I think I am not lucky enough to get git on my machine too. It does not install as well.
I have contacted git hub support too.

Is there any other way? Is it possible that I download files and put them somewhere in my project and include them?

Thanks

**Comment by tingletech** [comment]
```
pip install https://github.com/litchfield/django-fastsitemaps/archive/master.zip
```
or 
```
pip install https://github.com/litchfield/django-fastsitemaps/archive/master.tar.gz
```
will work if you don't have git installed
```
pip install https://github.com/litchfield/django-fastsitemaps/archive/9afce59dcd792649431fa919130dc461be0ee875.zip
```

or, in my `requirements.txt`

```
https://github.com/litchfield/django-fastsitemaps/archive/9afce59dcd792649431fa919130dc461be0ee875.zip#egg=django-fastsitemaps
```

works for me to get pinned to the current version

**Comment by litchfield** [comment]
Just `pip install django-fastsitemaps` should work

**Comment by tingletech** [comment]
@litchfield `pip install django-fastsitemaps` installs out of date version that does not work the django 1.9

**Comment by litchfield** [comment]
Sorted
